[server]
host = "127.0.0.1"
port = 8080
log_level = "info"

[database]
uri = "mongodb://localhost:27017"
database_name = "arbitrage_bot"
connection_timeout_ms = 5000
max_pool_size = 10

[cors]
allowed_origins = ["http://localhost:3000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE"]
allowed_headers = ["Authorization", "Accept", "Content-Type"]
supports_credentials = true

[indexer]
interval_minutes = 5
